# -*- coding: utf-8 -*-
"""Data_wrangling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v1JDSsAdP1x-fPkGQ9x2_DmcaPlv5yYS
"""

#Data Cleaning and Wrangling

import pandas as pd
import numpy as np

patients = pd.read_csv('patients.csv')
treatment = pd.read_csv('treatments.csv')
adverse = pd.read_csv('adverse_reactions.csv')

patients_copy = patients.copy()
treatment_copy = treatment.copy()
adverse_copy = adverse.copy()

patients_copy.info()

treatment_copy.info()



#Start with Completeness issue
# 1. missing values for contact details od 12 patients
# 2. Only 280 rows instead of 350
# 3. hba1c_change col had missing values
# refer the Data Assessing.py file to see these issue

patients_copy[patients_copy['address'].isnull()]

# unfortunatly we can't do anything to do anything about it

#hba1c_change thing
#sub hba1c_start from hba1c_end to get the change

treatment_copy['hba1c_change'] = treatment_copy['hba1c_start'] - treatment_copy['hba1c_end']

treatment_copy['hba1c_change'].isnull().sum()
treatment_copy.info()
treatment_copy.describe()

#this fixed the massive jump in describe seaction

# Tidiness Issue

#melt function
treatment_copy = pd.melt(treatment_copy, id_vars=['given_name', 'surname', 'hba1c_start', 'hba1c_end', 'hba1c_change'], var_name='treatment', value_name='dose')

treatment_copy = treatment_copy[treatment_copy['dose'] != "-"]

# Split the 'dose' column by hyphen, limiting the split to a maximum of 2
treatment_copy[['start', 'end']] = treatment_copy['dose'].str.split('-', n=1, expand=True)

treatment_copy.drop('dose', axis=1, inplace=True)
treatment_copy