# -*- coding: utf-8 -*-
"""Data Assessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JKEEWoK0cwYoNI372o3Hlb4UOQUhqxCu
"""

import pandas as pd

#to import 3 files for assessing
patients = pd.read_csv('patients.csv')
treatments = pd.read_csv('treatments.csv')
adverse_reactions = pd.read_csv('adverse_reactions.csv')

patients.shape
treatments.shape
adverse_reactions.shape

# patients.info()
# treatments.info()
# adverse_reactions.info()

patients

treatments

adverse_reactions

"""## **Quality Testing **

Treatment value:
- h1bac change columns - missing values
- medicine columns (auralin and	novodra) - has u attached to numbers
- only 280 rows, instead of 350 [thats the number of patients]
- Name and surname column is in lower case

Patients:
- zip code in decimal
- some zip code are of 4 digits
- states has either in full or short forms

adversial reaction:

Programic assesment (using pandas)
"""

import pandas as pd

patients.info()

# ** inputs from the .info() **
# address in some rows missing
# zip needs to be an object
# birthday - convert into date-datatype
# assigned_sex - change datatype

patients[patients['address'].isnull()]

treatments.info()

# ** inputs from the .info() **
#hba1c_change - missing values
#auralin and novodra - change to int

adverse_reactions.info()

patients.describe()

# min - height with 27 is very small
# weight of 48 also is weird

treatments.describe()

# 50% to 75% is very high jump
# so hba1c_change has incorrect value (so need to fix it)

patients.sample(5)

# inconsistant way of storing phone numbers

patients['address'].duplicated()

#to get info of all the patients with duplicate data
patients[patients['address'].duplicated()]

# duplicate data because of place holders - not useful data

#treaments table has - instead of nan of auralin and novodra

"""## ** Tidiness Issue**

Patients Table:
- email and contacts are in the same column and is inconsistent

Treatments Table:
- 3 variables stored in 2 colums i.e., auralin and novodra

Adverse Table:
- didn't have a create a seperate table could have placed this in treatments, by adding a column
"""

